GET http://localhost:8080/

###
GET http://localhost:8080/cars/serchCarNumber
Content-Type: application/json

{
      "CARNUMBER": 9689565

}


###
GET http://localhost:8080/cars/FindProductsByCar
Content-Type: application/json

{
      "MANUFACTURER": "מזדה",
      "MODEL": "מזדה 3",
      "MANUFACTURE_YEAR": "2009",
      "ENGINE_MODEL": "Z6",
      "CAPACITY": "1.6",
      "GAS": "בנזין",
      "GEAR": "אוטומט",
      "PROPULSION": "2X4",
      "DOORS": "4",
      "BODY": "סדאן",
      "YEAR_LIMIT": "עד 2009",
      "NOTE": "מזדה 3.588.292"
}

###
GET http://localhost:8080/cars/FindProductsByPARENT_GROUP
Content-Type: application/json

{
      "MANUFACTURER": "קיה",
      "MODEL": "פורטה",
      "MANUFACTURE_YEAR": "2018",
      "ENGINE_MODEL":"G4FG",
      "CAPACITY":"",
      "GAS": "בנזין",
      "GEAR":  "אוטומט",
      "PROPULSION": "2X4",
      "DOORS":  "4",
      "BODY": "סדאן",
      "YEAR_LIMIT":"",
      "NOTE":"פורטה.885.406",
      "PARENT_GROUP":"בולמי זעזועים וקפיצים"
}


###
GET http://localhost:8080/cars/FindCategorisByCar
Content-Type: application/json

{
      "MANUFACTURER": "מזדה",
      "MODEL": "מזדה 3",
      "MANUFACTURE_YEAR": "2009",
      "ENGINE_MODEL": "Z6",
      "GEAR": "אוטומט",
      "PROPULSION": "2X4",
      "DOORS": "4",
      "BODY": "סדאן",
      "YEAR_LIMIT": "עד 2009",
      "NOTE": "מזדה 3.588.292"
}

###
GET http://localhost:8080/cars/FindProductsByCar
Content-Type: application/json

{
      "MANUFACTURER": "קיה",
      "MODEL": "",
      "MANUFACTURE_YEAR": "",
      "ENGINE_MODEL":"",
      "CAPACITY":"",
      "GAS": "",
      "GEAR":  "",
      "PROPULSION": "",
      "DOORS":  "",
      "BODY": "",
      "YEAR_LIMIT":"",
      "NOTE":""
}


###
GET http://localhost:8080/cars/FindProductsById
Content-Type: application/json

{
      "CATALOG_NUMBER":"VKMA 03319"
}




###
GET http://localhost:8080/filter/getAllManufacturer


###
GET http://localhost:8080/filter/getAllModel
Content-Type: application/json

{
      "MANUFACTURER":"מזדה"
}

###
GET http://localhost:8080/filter/getAllmanufactureYear
Content-Type: application/json

{
      "MANUFACTURER":"מזדה",
      "MODEL":"מזדה 3"
}

###
GET http://localhost:8080/filter/getAllEngineModel
Content-Type: application/json

{
      "MANUFACTURER":"מזדה",
      "MODEL":"מזדה 3",
      "MANUFACTURE_YEAR": "2009"
}

###
GET http://localhost:8080/filter/getAllCapacity
Content-Type: application/json

{
      "MANUFACTURER":"טויוטה",
      "MODEL":"ונזה",
      "MANUFACTURE_YEAR": "2013",
      "ENGINE_MODEL":"1AR"
}

###
GET http://localhost:8080/filter/getAllGas
Content-Type: application/json

{
      "MANUFACTURER":"מזדה",
      "MODEL":"121",
      "MANUFACTURE_YEAR": "1994",
      "ENGINE_MODEL":"b3",
      "CAPACITY":"1.3"
}

###
GET http://localhost:8080/filter/getAllGear
Content-Type: application/json

{
      "MANUFACTURER":"מזדה",
      "MODEL":"121",
      "MANUFACTURE_YEAR": "1994",
      "ENGINE_MODEL":"b3",
      "CAPACITY":"1.3",
      "GAS": "בנזין"
}


###
GET http://localhost:8080/filter/getAllPropulsion
Content-Type: application/json

{
      "MANUFACTURER":"מזדה",
      "MODEL":"121",
      "MANUFACTURE_YEAR": "1994",
      "ENGINE_MODEL":"b3",
      "CAPACITY":"1.3",
      "GAS": "בנזין",
      "GEAR":"גיר רגיל"
}


###
GET http://localhost:8080/filter/getAllDoors
Content-Type: application/json

{
      "MANUFACTURER":"מזדה",
      "MODEL":"121",
      "MANUFACTURE_YEAR": "1994",
      "ENGINE_MODEL":"b3",
      "CAPACITY":"1.3",
      "GAS": "בנזין",
      "GEAR":"גיר רגיל",
      "PROPULSION": "2X4"
}

###
GET http://localhost:8080/filter/getAllBooy
Content-Type: application/json

{
      "MANUFACTURER":"מזדה",
      "MODEL":"121",
      "MANUFACTURE_YEAR": "1994",
      "ENGINE_MODEL":"b3",
      "CAPACITY":"1.3",
      "GAS": "בנזין",
      "GEAR":"גיר רגיל",
      "PROPULSION": "2X4",
      "DOORS": "0"
}


###
GET http://localhost:8080/cars/getParentGroup
Content-Type: application/json

{
      "MANUFACTURER": "קיה",
      "MODEL": "פורטה",
      "MANUFACTURE_YEAR": "2018",
      "YEAR_LIMIT":"עד 2013",
      "GEAR":  "אוטומט",
      "BODY": "סדאן",
      "DOORS":  "4",
      "GAS": "בנזין",
      "ENGINE_MODEL":"G4FG",
      "PROPULSION": "2X4",
      "CAPACITY":"",
      "NOTE":"פורטה.885.406"
}

###
GET http://localhost:8080/cars/getItemGroup
Content-Type: application/json

{
      "MANUFACTURER": "קיה",
      "MODEL": "פורטה",
      "MANUFACTURE_YEAR": "2018",
      "YEAR_LIMIT":"עד 2013",
      "GEAR":  "אוטומט",
      "BODY": "סדאן",
      "DOORS":  "4",
      "GAS": "בנזין",
      "ENGINE_MODEL":"G4FG",
      "PROPULSION": "2X4",
      "CAPACITY":"",
      "NOTE":"פורטה.885.406",
      "PARENTGROUP":"חלקי חשמל"
}

###
GET http://localhost:8080/cars/getChildGroup
Content-Type: application/json

{
      "MANUFACTURER": "קיה",
      "MODEL": "פורטה",
      "MANUFACTURE_YEAR": "2018",
      "YEAR_LIMIT":"עד 2013",
      "GEAR":  "אוטומט",
      "BODY": "סדאן",
      "DOORS":  "4",
      "GAS": "בנזין",
      "ENGINE_MODEL":"G4FG",
      "PROPULSION": "2X4",
      "CAPACITY":"",
      "NOTE":"פורטה.885.406",
      "PARENTGROUP":"חלקי חשמל",
      "ITEMGROUP":"חיישנים ויוניטים"
}





###
GET http://localhost:8080/cars/FindProductsByCHILD_GROUP
Content-Type: application/json

{
  "MANUFACTURER" : "אודי",
    "MODEL" : "A3",
    "MANUFACTURE_YEAR" :"",
    "YEAR_LIMIT" :"",
    "GEAR" :"",
    "BODY" :"",
    "DOORS" :"",
    "ENGINE_MODEL" :"",
    "PROPULSION" :"",
    "NOTE" :"",
    "PARENT_GROUP" :"מיסבים ונבות לגלגלים",
    "ITEM_GROUP" :"מיסבים ונבות לגלגל",
    "CHILD_GROUP" :"נבה אחורית מושלמת"
}

###
GET http://localhost:8080/cars/FindProductsByITEM_GROUP
Content-Type: application/json

{
      "MANUFACTURER": "קיה",
      "MODEL": "פורטה",
      "MANUFACTURE_YEAR": "2018",
      "ENGINE_MODEL":"G4FG",
      "CAPACITY":"",
      "GAS": "בנזין",
      "GEAR":  "אוטומט",
      "PROPULSION": "2X4",
      "DOORS":  "4",
      "BODY": "סדאן",
      "YEAR_LIMIT":"",
      "NOTE":"פורטה.885.406",
      "PARENT_GROUP":"בולמי זעזועים וקפיצים",
      "ITEM_GROUP":"בולמי זעזועים"
}

###
GET http://localhost:8080/filter/getAlternativeSKU
Content-Type: application/json

{
      "SKU": "SWTC-18"
}

###
GET http://localhost:8080/cars/getInfoBySKU
Content-Type: application/json

{
      "CATALOG_NUMBER":"VKMA 03319",
      "CHILD_GROUP":"סט טיימינג",
      "DESCRIPTION_NOTE":""
}

###
GET http://localhost:8080/itemCard/getItemBrand
Content-Type: application/json

{
      "CATALOG_NUMBER":"SWTC-58",
      "CHILD_GROUP":"חיישן קמשפט",
      "DESCRIPTION_NOTE":""
}

###
GET http://localhost:8080/users/logIn
Content-Type: application/json

{
      "userName":"000",
      "Password":"12345"
}

###
GET http://localhost:8080/favorits/getFavoritsList
Content-Type: application/json

{
      "userName":"1",
      "cardCode":"21234"
}


###
GET http://localhost:8080/armor/getArmorsList
Content-Type: application/json

{
      "userName":"1",
      "cardCode":"21234"
}


###
GET http://localhost:8080/cart/addItemToCart
Content-Type: application/json

{
      "userName":"1",
      "cardCode":"21234",
      "item_code":"G8803",
      "amountToBy":0
}


###
GET http://localhost:8080/cars/getProdactsBySerch
Content-Type: application/json

{
      "serchData": "בולם"
}




###
GET http://localhost:8080/itemCard/getItemBrandByCar
Content-Type: application/json

{
      "MANUFACTURER": "יונדאי",
      "MODEL": "",
      "MANUFACTURE_YEAR": "",
      "ENGINE_MODEL":"",
      "CAPACITY":"",
      "GAS": "",
      "GEAR":  "",
      "PROPULSION": "",
      "DOORS":  "",
      "BODY": "",
      "YEAR_LIMIT":"",
      "NOTE":"",
      "DESCRIPTION_NOTE":"ימין",
      "CHILD_GROUP":"בולם אחורי"
}



###
GET http://localhost:8080/filter/getComplitSerch
Content-Type: application/json

{
      "search_value": "בולם"
}


###
GET http://localhost:8080/users/getWhatsAppUsers


###
GET http://localhost:8080/filter/getShippingExitTime
Content-Type: application/json

{
      "search_value": "יפו - בת-ים"
}


###
GET http://localhost:8080/filter/getAllDeliverys


###
GET http://localhost:8080/armor/getArmorsInStok
Content-Type: application/json

{
      "userName":"1",
      "cardCode":"21234"
}



###
GET https://localhost:443/filter/getAllDeliverys


###
POST  https://localhost:443/cron/updatePaginated


###
GET https://api.recordltd.co.il/cars/FindCategorisByCar?MANUFACTURER=דייהטסו&MODEL=טיריוס&MANUFACTURE_YEAR=2005&ENGINE_MODEL=&GEAR=&PROPULSION=&DOORS=&BODY=&YEAR_LIMIT=&NOTE=
